services:
  django: &django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my_scores_django
    container_name: my_scores_django
    depends_on:
      - redis
    volumes:
      - static_volume:/static
    ports:
      - '8007:8007'

  redis:
    image: docker.io/redis:6
    container_name: my_scores_redis_data
    volumes:
      - my_scores_redis_data:/data

volumes:
  static_volume: {}
  my_scores_redis_data: {}
